-- =====================================================================
-- Retail Sales Analysis — SQL Script
-- Description: Creates the sales table, inserts sample data, and answers
-- the sales-analysis questions (Parts A-H).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. CREATE TABLE
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS sales;

CREATE TABLE sales (
    sale_id INT PRIMARY KEY,
    product VARCHAR(50),
    category VARCHAR(50),
    region VARCHAR(50),
    sales_rep VARCHAR(50),
    quantity INT,
    unit_price DECIMAL(12,2),
    sales_amount DECIMAL(12,2),
    sale_date DATE,
    customer_type VARCHAR(50)
);

-- ---------------------------------------------------------------------
-- 2. INSERT SAMPLE DATA
-- ---------------------------------------------------------------------
INSERT INTO sales (
    sale_id, product, category, region, sales_rep,
    quantity, unit_price, sales_amount, sale_date, customer_type
)
VALUES
(1, 'Laptop', 'Electronics', 'Lagos', 'Ada', 2, 450000, 900000, '2026-01-05', 'Corporate'),
(2, 'Phone', 'Electronics', 'Abuja', 'John', 5, 250000, 1250000, '2026-01-08', 'Individual'),
(3, 'Chair', 'Furniture', 'Lagos', 'Mary', 10, 45000, 450000, '2026-01-15', 'Corporate'),
(4, 'Desk', 'Furniture', 'Kano', 'John', 4, 120000, 480000, '2026-01-21', 'Individual'),
(5, 'Laptop', 'Electronics', 'Abuja', 'Ada', 1, 450000, 450000, '2026-02-02', 'Individual'),
(6, 'Phone', 'Electronics', 'Lagos', 'Mary', 3, 250000, 750000, '2026-02-07', 'Corporate'),
(7, 'Tablet', 'Electronics', 'Kano', 'David', 4, 180000, 720000, '2026-02-11', 'Individual'),
(8, 'Printer', 'Electronics', 'Port Harcourt', 'Grace', 3, 150000, 450000, '2026-02-18', 'Corporate'),
(9, 'Desk', 'Furniture', 'Abuja', 'John', 6, 120000, 720000, '2026-02-24', 'Corporate'),
(10, 'Chair', 'Furniture', 'Kano', 'David', 12, 45000, 540000, '2026-03-03', 'Individual'),
(11, 'Laptop', 'Electronics', 'Lagos', 'Ada', 3, 450000, 1350000, '2026-03-06', 'Corporate'),
(12, 'Phone', 'Electronics', 'Port Harcourt', 'Grace', 4, 250000, 1000000, '2026-03-10', 'Individual'),
(13, 'Tablet', 'Electronics', 'Abuja', 'Mary', 2, 180000, 360000, '2026-03-14', 'Individual'),
(14, 'Printer', 'Electronics', 'Lagos', 'David', 5, 150000, 750000, '2026-03-18', 'Corporate'),
(15, 'Desk', 'Furniture', 'Port Harcourt', 'John', 5, 120000, 600000, '2026-03-22', 'Corporate'),
(16, 'Chair', 'Furniture', 'Abuja', 'Grace', 8, 45000, 360000, '2026-04-02', 'Individual'),
(17, 'Laptop', 'Electronics', 'Kano', 'Ada', 2, 450000, 900000, '2026-04-06', 'Corporate'),
(18, 'Phone', 'Electronics', 'Lagos', 'Mary', 6, 250000, 1500000, '2026-04-09', 'Corporate'),
(19, 'Tablet', 'Electronics', 'Port Harcourt', 'David', 5, 180000, 900000, '2026-04-13', 'Individual'),
(20, 'Printer', 'Electronics', 'Abuja', 'Grace', 7, 150000, 1050000, '2026-04-17', 'Corporate'),
(21, 'Desk', 'Furniture', 'Lagos', 'John', 3, 120000, 360000, '2026-04-21', 'Individual'),
(22, 'Chair', 'Furniture', 'Port Harcourt', 'Mary', 15, 45000, 675000, '2026-05-01', 'Corporate'),
(23, 'Laptop', 'Electronics', 'Abuja', 'Ada', 4, 450000, 1800000, '2026-05-05', 'Corporate'),
(24, 'Phone', 'Electronics', 'Kano', 'David', 2, 250000, 500000, '2026-05-09', 'Individual'),
(25, 'Tablet', 'Electronics', 'Lagos', 'Grace', 6, 180000, 1080000, '2026-05-12', 'Corporate'),
(26, 'Printer', 'Electronics', 'Port Harcourt', 'John', 4, 150000, 600000, '2026-05-16', 'Individual'),
(27, 'Desk', 'Furniture', 'Kano', 'Mary', 7, 120000, 840000, '2026-05-20', 'Corporate'),
(28, 'Chair', 'Furniture', 'Lagos', 'Grace', 20, 45000, 900000, '2026-05-24', 'Individual'),
(29, 'Laptop', 'Electronics', 'Port Harcourt', 'Ada', 1, 450000, 450000, '2026-06-02', 'Individual'),
(30, 'Phone', 'Electronics', 'Abuja', 'John', 5, 250000, 1250000, '2026-06-07', 'Corporate');

-- ---------------------------------------------------------------------
-- PART A: AGGREGATE FUNCTIONS
-- ---------------------------------------------------------------------

-- Question 1: Total revenue generated by the company
SELECT
    SUM(sales_amount) AS total_revenue
FROM sales;

-- Question 2: Total number of sales transactions

SELECT
    COUNT(*) AS total_transactions
FROM sales;

-- Question 3: Average sales amount per transaction
SELECT
    AVG(sales_amount) AS average_transaction
FROM sales;

-- Question 4: Highest and lowest sales amounts
SELECT
    MAX(sales_amount) AS highest_sales_amount,
    MIN(sales_amount) AS lowest_sales_amount
FROM sales;

-- ---------------------------------------------------------------------
-- PART B: GROUP BY
-- ---------------------------------------------------------------------

-- Question 5: Total sales by region, highest to lowest
SELECT
    region,
    SUM(sales_amount) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC;

-- Question 6: Total sales by product
SELECT
    product,
    SUM(sales_amount) AS total_sales
FROM sales
GROUP BY product;

-- Question 7: Number of transactions by sales representative
SELECT
    sales_rep,
    COUNT(*) AS total_transactions
FROM sales
GROUP BY sales_rep;

-- Question 8: Average transaction amount by region
SELECT
    region,
    AVG(sales_amount) AS average_transaction
FROM sales
GROUP BY region;

-- Question 9: Total sales for every region and product combination
SELECT
    region,
    product,
    SUM(sales_amount) AS total_sales
FROM sales
GROUP BY region, product;

-- ---------------------------------------------------------------------
-- PART C: HAVING
-- ---------------------------------------------------------------------

-- Question 10: Regions with total sales greater than 1,000,000
SELECT
    region,
    SUM(sales_amount) AS total_sales
FROM sales
GROUP BY region
HAVING SUM(sales_amount) > 1000000;

-- Question 11: Products with average transaction amount greater than 500,000
SELECT
    product,
    AVG(sales_amount) AS average_sales
FROM sales
GROUP BY product
HAVING AVG(sales_amount) > 500000;

-- ---------------------------------------------------------------------
-- PART D: STRING FUNCTIONS
-- ---------------------------------------------------------------------

-- Question 12: Sales representatives names in uppercase
SELECT
    sales_rep,
    UPPER(sales_rep) AS uppercase_name
FROM sales;

-- Question 13: Product names in lowercase
SELECT
    product,
    LOWER(product) AS lowercase_product
FROM sales;

-- Question 14: Combine sales representative and region
SELECT
    sales_rep,
    region,
    CONCAT(sales_rep, ' - ', region) AS rep_location
FROM sales;

-- Question 15: Product name and number of characters
SELECT
    product,
    LENGTH(product) AS product_name_length
FROM sales;

-- ---------------------------------------------------------------------
-- PART E: DATE FUNCTIONS
-- ---------------------------------------------------------------------

-- Question 16: Extract year and month from sale_date
SELECT
    EXTRACT(YEAR FROM sale_date) AS sale_year,
    EXTRACT(MONTH FROM sale_date) AS sale_month
FROM sales;

-- Question 17: Total sales by month

SELECT
    EXTRACT(MONTH FROM sale_date) AS sale_month,
    TO_CHAR(sale_date, 'MONTH') AS sale_month_name,
	SUM(sales_amount) AS total_sales
FROM sales
GROUP BY 
    EXTRACT(MONTH FROM sale_date),
    TO_CHAR(sale_date, 'MONTH')      
ORDER BY 
    sale_month;

-- Question 18: Number of transactions by month
	
SELECT
    TO_CHAR(DATE_TRUNC('MONTH', sale_date), 'Month') AS sale_month,
    COUNT(*) AS total_transactions
FROM sales
GROUP BY DATE_TRUNC('MONTH', sale_date)
ORDER BY DATE_TRUNC('MONTH', sale_date);


-- ---------------------------------------------------------------------
-- PART F: CASE STATEMENTS
-- ---------------------------------------------------------------------

-- Question 19: Classify each transaction by value
SELECT
    product,
    sales_amount,
    CASE
        WHEN sales_amount >= 1000000 THEN 'High Value'
        WHEN sales_amount >= 500000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS transaction_category
FROM sales;

-- Question 20: Classify customers
SELECT
    customer_type,
    CASE customer_type
        WHEN 'Corporate' THEN 'Business Customer'
        WHEN 'Individual' THEN 'Retail Customer'
    END AS customer_group
FROM sales;

-- ---------------------------------------------------------------------
-- PART G: CASE + AGGREGATE FUNCTIONS
-- ---------------------------------------------------------------------

-- Question 23: Total revenue from Corporate customers
SELECT
    SUM(
        CASE
            WHEN customer_type = 'Corporate' THEN sales_amount
            ELSE 0
        END
    ) AS corporate_revenue
FROM sales;

-- Question 24: Corporate and Individual revenue
SELECT
    SUM(
        CASE
            WHEN customer_type = 'Corporate' THEN sales_amount
            ELSE 0
        END
    ) AS corporate_revenue,
    SUM(
        CASE
            WHEN customer_type = 'Individual' THEN sales_amount
            ELSE 0
        END
    ) AS individual_revenue
FROM sales;

-- Question 25: Number of High Value transactions by region
SELECT
    region,
    COUNT(
        CASE
            WHEN sales_amount >= 1000000 THEN 1
        END
    ) AS high_value_transactions
FROM sales
GROUP BY region;

-- ---------------------------------------------------------------------
-- PART H: BUSINESS ANALYSIS CHALLENGE
-- ---------------------------------------------------------------------

-- Regional performance report
SELECT
    region,
    SUM(sales_amount) AS total_revenue,
    COUNT(*) AS number_of_transactions,
    AVG(sales_amount) AS average_transaction,
    SUM(
        CASE
            WHEN customer_type = 'Corporate' THEN sales_amount
            ELSE 0
        END
    ) AS corporate_revenue,
    SUM(
        CASE
            WHEN customer_type = 'Individual' THEN sales_amount
            ELSE 0
        END
    ) AS individual_revenue
FROM sales
GROUP BY region
ORDER BY total_revenue DESC;

-- ---------------------------------------------------------------------
-- FINAL ANALYSIS SUPPORT QUERIES
-- ---------------------------------------------------------------------

-- Region with highest and lowest revenue
SELECT
    region,
    SUM(sales_amount) AS total_revenue
FROM sales
GROUP BY region
ORDER BY total_revenue DESC;

-- Product with highest revenue
SELECT
    product,
    SUM(sales_amount) AS total_revenue
FROM sales
GROUP BY product
ORDER BY total_revenue DESC;

-- Sales representative with the highest number of transactions
SELECT
    sales_rep,
    COUNT(*) AS total_transactions
FROM sales
GROUP BY sales_rep
ORDER BY total_transactions DESC;

-- Revenue by customer type
SELECT
    customer_type,
    SUM(sales_amount) AS total_revenue
FROM sales
GROUP BY customer_type
ORDER BY total_revenue DESC;

-- Monthly Sales Performance

SELECT
    DATE_TRUNC('MONTH', sale_date) AS sale_month,
	COUNT(sale_id) AS total_orders,
    SUM(sales_amount) AS total_sales,
	ROUND(AVG(sales_amount), 2) AS average_order_value
FROM sales
GROUP BY DATE_TRUNC('MONTH', sale_date)
ORDER BY total_sales DESC;

-- Total High Value transactions
SELECT
    COUNT(*) AS high_value_transactions
FROM sales
WHERE sales_amount >= 1000000;























